// <auto-generated />
using System;
using System.Text.Json;
using AgriculturePlatform.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgriculturePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604072651_Foreignkeyadded")]
    partial class Foreignkeyadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PasswordResetExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<JsonDocument>("NewValue")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("OldValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("AdminId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("CompanyId", "CreatedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("text");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("WorkerId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("AlertType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("Severity");

                    b.HasIndex("CompanyId", "IsResolved");

                    b.HasIndex("FieldId", "IsResolved");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CropType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpectedHarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<string>("GrowthStage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("PlantingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("FieldId");

                    b.HasIndex("PlantingDate");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("CropCycles");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AreaHectares")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SoilType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("FieldName");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<string>("CropHealth")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ObservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PestDetected")
                        .HasColumnType("boolean");

                    b.Property<string>("PestType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("FieldId", "ObservationDate");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SensorType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("SensorType");

                    b.HasIndex("CompanyId", "RecordedAt");

                    b.HasIndex("FieldId", "RecordedAt");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("RainfallMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WindSpeed")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FieldId", "RecordedAt");

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("CompanyId", "Role");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.WorkerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FieldId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TaskName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("FieldId");

                    b.HasIndex("CompanyId", "Status");

                    b.HasIndex("Status", "DueDate");

                    b.HasIndex("WorkerId", "Status");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.Harvest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HarvestedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("QualityGrade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("FieldId");

                    b.HasIndex("HarvestedBy");

                    b.HasIndex("CompanyId", "HarvestDate");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.QualityCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CheckedBy")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DefectPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("FinalGrade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("HarvestId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MoisturePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CheckedBy");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HarvestId");

                    b.ToTable("QualityChecks");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.YieldReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("AvgQualityGrade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("TotalYieldKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("YieldPerHectareKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("CompanyId", "ReportDate");

                    b.ToTable("YieldReports");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("Admins")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Creator")
                        .WithMany("CreatedAdmins")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.AuditLog", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany("AuditLogs")
                        .HasForeignKey("WorkerId");

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Notification", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Notifications")
                        .HasForeignKey("AdminId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("Notifications")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany("Notifications")
                        .HasForeignKey("WorkerId");

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Alert", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Alerts")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("Alerts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("Alerts")
                        .HasForeignKey("CropCycleId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("Alerts")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("CropCycle");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("CropCycles")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("CropCycles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("CropCycles")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Fields")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("Fields")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Observation", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Observations")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("Observations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("Observations")
                        .HasForeignKey("CropCycleId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("Observations")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany("Observations")
                        .HasForeignKey("WorkerId");

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("CropCycle");

                    b.Navigation("Field");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.SensorReading", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("SensorReadings")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("SensorReadings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("SensorReadings")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("SensorReadings")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("CropCycle");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.WeatherData", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("WeatherData")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("WeatherData")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("WeatherData")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Workers")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("Workers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.WorkerTask", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Tasks")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("Tasks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("Tasks")
                        .HasForeignKey("CropCycleId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("Tasks")
                        .HasForeignKey("FieldId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("CropCycle");

                    b.Navigation("Field");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.Harvest", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Harvests")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("Harvests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("Harvests")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("Harvests")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Harvester")
                        .WithMany("Harvests")
                        .HasForeignKey("HarvestedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");

                    b.Navigation("Approver");

                    b.Navigation("Company");

                    b.Navigation("CropCycle");

                    b.Navigation("Field");

                    b.Navigation("Harvester");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.QualityCheck", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("QualityChecks")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Checker")
                        .WithMany("QualityChecks")
                        .HasForeignKey("CheckedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("QualityChecks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.YieldReports.Harvest", "Harvest")
                        .WithMany("QualityChecks")
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Approver");

                    b.Navigation("Checker");

                    b.Navigation("Company");

                    b.Navigation("Harvest");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.YieldReport", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("YieldReports")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Company", "Company")
                        .WithMany("YieldReports")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("YieldReports")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Company");

                    b.Navigation("CropCycle");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedAdmins");

                    b.Navigation("CropCycles");

                    b.Navigation("Fields");

                    b.Navigation("Harvests");

                    b.Navigation("Notifications");

                    b.Navigation("Observations");

                    b.Navigation("QualityChecks");

                    b.Navigation("SensorReadings");

                    b.Navigation("Tasks");

                    b.Navigation("WeatherData");

                    b.Navigation("Workers");

                    b.Navigation("YieldReports");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Company", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Alerts");

                    b.Navigation("AuditLogs");

                    b.Navigation("CropCycles");

                    b.Navigation("Fields");

                    b.Navigation("Harvests");

                    b.Navigation("Notifications");

                    b.Navigation("Observations");

                    b.Navigation("QualityChecks");

                    b.Navigation("SensorReadings");

                    b.Navigation("Tasks");

                    b.Navigation("WeatherData");

                    b.Navigation("Workers");

                    b.Navigation("YieldReports");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Harvests");

                    b.Navigation("Observations");

                    b.Navigation("SensorReadings");

                    b.Navigation("Tasks");

                    b.Navigation("YieldReports");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("CropCycles");

                    b.Navigation("Harvests");

                    b.Navigation("Observations");

                    b.Navigation("SensorReadings");

                    b.Navigation("Tasks");

                    b.Navigation("WeatherData");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Harvests");

                    b.Navigation("Notifications");

                    b.Navigation("Observations");

                    b.Navigation("QualityChecks");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.Harvest", b =>
                {
                    b.Navigation("QualityChecks");
                });
#pragma warning restore 612, 618
        }
    }
}
