// <auto-generated />
using System;
using System.Text.Json;
using AgriculturePlatform.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgriculturePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705201731_AddHarvestImageFields")]
    partial class AddHarvestImageFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PasswordResetExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FarmId");

                    b.HasIndex("IsActive");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("FarmId")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<JsonDocument>("NewValue")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("OldValue")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("AdminId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("FarmId", "CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("TotalLandHectares")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("text");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("FarmId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FarmId");

                    b.HasIndex("WorkerId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("AdminId", "IsRevoked");

                    b.HasIndex("WorkerId", "IsRevoked");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("AlertType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SensorReadingId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SensorValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("AlertType");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("SensorReadingId");

                    b.HasIndex("Severity");

                    b.HasIndex("FarmId", "IsResolved");

                    b.HasIndex("FieldId", "IsResolved");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.AlertThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<string>("GrowthStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MinValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("NotificationEmails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("IsActive");

                    b.HasIndex("FarmId", "CropType", "GrowthStage", "SensorType")
                        .IsUnique();

                    b.ToTable("AlertThresholds");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CropType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpectedHarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<string>("GrowthStage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PlantingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("FieldId");

                    b.HasIndex("PlantingDate");

                    b.HasIndex("FarmId", "Status");

                    b.ToTable("CropCycles");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AreaHectares")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("double precision");

                    b.Property<string>("SoilType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("FieldName");

                    b.HasIndex("FarmId", "Status");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalImagePaths")
                        .HasColumnType("jsonb");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("AdminId1")
                        .HasColumnType("integer");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Admin's questions or comments on the observation");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<string>("CropHealth")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<string>("FlagReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("outlier, inconsistent_data, missing_info, duplicate");

                    b.Property<string>("ImageCaption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageMetadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageVerificationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsImageVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ObservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PestType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When the observation was validated");

                    b.Property<int?>("ValidatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasComment("pending, verified, questioned, invalid");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkerResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Worker's response to admin questions");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("AdminId1");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("ObservationDate")
                        .HasDatabaseName("IX_Observations_Date");

                    b.HasIndex("ValidatedBy")
                        .HasDatabaseName("IX_Observations_ValidatedBy");

                    b.HasIndex("ValidationStatus")
                        .HasDatabaseName("IX_Observations_ValidationStatus");

                    b.HasIndex("WorkerId")
                        .HasDatabaseName("IX_Observations_WorkerId");

                    b.HasIndex("FarmId", "ValidationStatus")
                        .HasDatabaseName("IX_Observations_Farm_ValidationStatus");

                    b.HasIndex("FieldId", "ObservationDate")
                        .HasDatabaseName("IX_Observations_Field_Date");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SensorType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("SensorType");

                    b.HasIndex("FarmId", "RecordedAt");

                    b.HasIndex("FieldId", "RecordedAt");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.WeatherAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AcknowledgedBy")
                        .HasColumnType("integer");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AlertTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double?>("RainfallMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<double?>("WindSpeed")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AcknowledgedBy");

                    b.HasIndex("AdminId");

                    b.HasIndex("AlertTime");

                    b.HasIndex("AlertType");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FieldId");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("Severity");

                    b.HasIndex("FarmId", "FieldId");

                    b.ToTable("WeatherAlerts");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<double?>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("RainfallMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<double?>("WindSpeed")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FieldId", "RecordedAt");

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("text");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("FarmId", "Role");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.WorkerFieldAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkerId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("AssignedDate");

                    b.HasIndex("FieldId");

                    b.HasIndex("IsActive");

                    b.HasIndex("WorkerId");

                    b.HasIndex("WorkerId1");

                    b.HasIndex("FarmId", "WorkerId", "FieldId");

                    b.ToTable("WorkerFieldAssignments");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.WorkerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TaskName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CropCycleId");

                    b.HasIndex("FieldId");

                    b.HasIndex("FarmId", "Status");

                    b.HasIndex("Status", "DueDate");

                    b.HasIndex("WorkerId", "Status");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.Harvest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalImagePaths")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("AdminId1")
                        .HasColumnType("integer");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HarvestMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("HarvestedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ImageCaption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageMetadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("PricePerKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("QualityGrade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SubmittedBy")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("WorkerResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("AdminId1");

                    b.HasIndex("ApprovalStatus")
                        .HasDatabaseName("IX_Harvests_ApprovalStatus");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BatchNumber")
                        .HasDatabaseName("IX_Harvests_BatchNumber");

                    b.HasIndex("CropCycleId")
                        .HasDatabaseName("IX_Harvests_CropCycleId");

                    b.HasIndex("FieldId");

                    b.HasIndex("FieldId1");

                    b.HasIndex("HarvestedBy")
                        .HasDatabaseName("IX_Harvests_HarvestedBy");

                    b.HasIndex("SubmittedBy")
                        .HasDatabaseName("IX_Harvests_SubmittedBy");

                    b.HasIndex("FarmId", "HarvestDate")
                        .HasDatabaseName("IX_Harvests_Farm_Date");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.QualityCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDING");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CheckedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DefectPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<string>("FinalGrade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("HarvestId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MoisturePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("WorkerResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CheckDate");

                    b.HasIndex("CheckedBy");

                    b.HasIndex("FarmId");

                    b.HasIndex("HarvestId");

                    b.ToTable("QualityChecks");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.YieldReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("AdminId1")
                        .HasColumnType("integer");

                    b.Property<decimal>("AveragePricePerKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("AverageQualityGrade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("AverageYieldPerHectare")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CropCycleId")
                        .HasColumnType("integer");

                    b.Property<string>("CropTypeBreakdownJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExportedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<string>("FieldBreakdownJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("FieldId")
                        .HasColumnType("integer");

                    b.Property<string>("FileFormat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonthlyTrendJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("NextScheduledRun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PassRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("QualityDistributionJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("RejectionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ScheduleCron")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalHarvests")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("TotalYieldKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("AdminId1");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_YieldReports_CreatedAt");

                    b.HasIndex("CropCycleId")
                        .HasDatabaseName("IX_YieldReports_CropCycleId");

                    b.HasIndex("ExportedBy");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("IX_YieldReports_FieldId");

                    b.HasIndex("IsScheduled")
                        .HasDatabaseName("IX_YieldReports_IsScheduled");

                    b.HasIndex("NextScheduledRun")
                        .HasDatabaseName("IX_YieldReports_NextScheduledRun");

                    b.HasIndex("ReportType")
                        .HasDatabaseName("IX_YieldReports_ReportType");

                    b.HasIndex("FarmId", "StartDate", "EndDate")
                        .HasDatabaseName("IX_YieldReports_Farm_DateRange");

                    b.ToTable("YieldReports");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Creator")
                        .WithMany("CreatedAdmins")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("Admins")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.AuditLog", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("AuditLogs")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany("AuditLogs")
                        .HasForeignKey("WorkerId");

                    b.Navigation("Admin");

                    b.Navigation("Farm");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Notification", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Notifications")
                        .HasForeignKey("AdminId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("Notifications")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany("Notifications")
                        .HasForeignKey("WorkerId");

                    b.Navigation("Admin");

                    b.Navigation("Farm");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.RefreshToken", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Admin");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Alert", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Alerts")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("Alerts")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("Alerts")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("Alerts")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.SensorReading", null)
                        .WithMany("Alerts")
                        .HasForeignKey("SensorReadingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("CropCycle");

                    b.Navigation("Farm");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.AlertThreshold", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("CropCycles")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("CropCycles")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("CropCycles")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Farm");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Fields")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("Fields")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Observation", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", null)
                        .WithMany("Observations")
                        .HasForeignKey("AdminId1");

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("Observations")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("Observations")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("Observations")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Validator")
                        .WithMany()
                        .HasForeignKey("ValidatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany("Observations")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("CropCycle");

                    b.Navigation("Farm");

                    b.Navigation("Field");

                    b.Navigation("Validator");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.SensorReading", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("SensorReadings")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("SensorReadings")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("SensorReadings")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("SensorReadings")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("CropCycle");

                    b.Navigation("Farm");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.WeatherAlert", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Acknowledger")
                        .WithMany()
                        .HasForeignKey("AcknowledgedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acknowledger");

                    b.Navigation("Admin");

                    b.Navigation("Farm");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.WeatherData", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("WeatherData")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("WeatherData")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("WeatherData")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Farm");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Workers")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("Workers")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.WorkerFieldAssignment", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", null)
                        .WithMany("AssignedFields")
                        .HasForeignKey("WorkerId1");

                    b.Navigation("Admin");

                    b.Navigation("Farm");

                    b.Navigation("Field");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.WorkerTask", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("Tasks")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("Tasks")
                        .HasForeignKey("CropCycleId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("Tasks")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany("Tasks")
                        .HasForeignKey("FieldId");

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Worker")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("CropCycle");

                    b.Navigation("Farm");

                    b.Navigation("Field");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.Harvest", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", null)
                        .WithMany("Harvests")
                        .HasForeignKey("AdminId1");

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("Harvests")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("Harvests")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", null)
                        .WithMany("Harvests")
                        .HasForeignKey("FieldId1");

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Harvester")
                        .WithMany("Harvests")
                        .HasForeignKey("HarvestedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("Approver");

                    b.Navigation("CropCycle");

                    b.Navigation("Farm");

                    b.Navigation("Field");

                    b.Navigation("Harvester");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.QualityCheck", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany("QualityChecks")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", "Checker")
                        .WithMany("QualityChecks")
                        .HasForeignKey("CheckedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("QualityChecks")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.YieldReports.Harvest", "Harvest")
                        .WithMany("QualityChecks")
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Approver");

                    b.Navigation("Checker");

                    b.Navigation("Farm");

                    b.Navigation("Harvest");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.YieldReport", b =>
                {
                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", null)
                        .WithMany("YieldReports")
                        .HasForeignKey("AdminId1");

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", "CropCycle")
                        .WithMany("YieldReports")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", "Exporter")
                        .WithMany()
                        .HasForeignKey("ExportedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", "Farm")
                        .WithMany("YieldReports")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("CropCycle");

                    b.Navigation("Exporter");

                    b.Navigation("Farm");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Admin", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedAdmins");

                    b.Navigation("CropCycles");

                    b.Navigation("Fields");

                    b.Navigation("Harvests");

                    b.Navigation("Notifications");

                    b.Navigation("Observations");

                    b.Navigation("QualityChecks");

                    b.Navigation("SensorReadings");

                    b.Navigation("Tasks");

                    b.Navigation("WeatherData");

                    b.Navigation("Workers");

                    b.Navigation("YieldReports");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.AdminEntities.Farm", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Alerts");

                    b.Navigation("AuditLogs");

                    b.Navigation("CropCycles");

                    b.Navigation("Fields");

                    b.Navigation("Harvests");

                    b.Navigation("Notifications");

                    b.Navigation("Observations");

                    b.Navigation("QualityChecks");

                    b.Navigation("SensorReadings");

                    b.Navigation("Tasks");

                    b.Navigation("WeatherData");

                    b.Navigation("Workers");

                    b.Navigation("YieldReports");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.CropCycle", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Harvests");

                    b.Navigation("Observations");

                    b.Navigation("SensorReadings");

                    b.Navigation("Tasks");

                    b.Navigation("YieldReports");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.Field", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("CropCycles");

                    b.Navigation("Harvests");

                    b.Navigation("Observations");

                    b.Navigation("SensorReadings");

                    b.Navigation("Tasks");

                    b.Navigation("WeatherData");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.CropMonitoring.SensorReading", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.WorkerManagement.Worker", b =>
                {
                    b.Navigation("AssignedFields");

                    b.Navigation("AuditLogs");

                    b.Navigation("Harvests");

                    b.Navigation("Notifications");

                    b.Navigation("Observations");

                    b.Navigation("QualityChecks");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AgriculturePlatform.Domain.Entities.YieldReports.Harvest", b =>
                {
                    b.Navigation("QualityChecks");
                });
#pragma warning restore 612, 618
        }
    }
}
